### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amunozdev** [Mmaxi1720/desafio-m6#1]
Buenas Maxi, al momento de ingresar a una sala, tira el siguiente error `Uncaught TypeError: Cannot read properties of null (reading 'owner')` y no se puede avanzar:
![Captura de pantalla de 2022-05-01 10-58-42](https://user-images.githubusercontent.com/77214476/166149285-73474dca-8370-4396-b1c1-519d2e2ab3df.png)

**Comment by Mmaxi1720** [comment]
Buenas Alex.
Ahi hice unas modificaciones en el render, me deja jugar ingresando desde una sala.
porfa fijate si esta bien ahora.
Muchas gracias por el tiempo
