### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [Mmaxi1720/desafio-m6#2]
Buenas Maxi,
Felicitaciones por llegar hasta acá
Estuve probando la app y te quedo muy bien realizada.

Fijate el tema del archivo key.json ya que ahí tenes todas las credenciales de tu cuenta de firebase, te recomendaría sacarlo y subir esas configuraciones / credenciales como variables de entorno.

Algo que estaría piola que puedas agregarle a la app es que cuando yo creo una sala y entro en la page para compartir mi código, que esa page tenga un timer X por si la otra persona no ingresa y que te vuelva a llevar al menú o te de un aviso.

Otro tema que no hace al desafío pero que si me gustaría recomendarte es que seas un poco más especifico en tus commits. Obvio que esto es práctica pero para alguien técnico que mira tu portfolio/github cuando salgas a buscar trabajo los nombres "otro commit, algunos cambios, etc,etc" no le dice nada y esta bueno mostrar esa "buena práctica" de commits un poco más específicos.

Éxitos en el próximo modulo!

**Comment by Mmaxi1720** [comment]
Buenas Fer.
Todo lo que ayude para mejorar siempre es bien recibido.
Te agradezco por tomarte el tiempo de verlo
Voy tener en cuenta todos los puntos que me dijiste.
Gracias
