### ISSUE TITLE
Devolución

### ISSUE THREAD

**Issue by amunozdev** [Mmaxi1720/desafio-m6#3]
Buenas Maxi, felicitaciones por terminar el desafío, la verdad esa muy bueno

- Hay una cosa que habría que corregir, cuando ninguno de los dos jugadores selecciona una mano el juego sigue adelante y por alguna razón simula una jugada y el resultado de la jugada se va sumando al score 
- Creo que lo mejor sería redirigir a los jugadores a la page anterior, es decir a /instructions, ya que ninguno de los dos selecciono nada, por lo tanto, seria empate

A no aflojar que ya casi lo tenes! un saludo

**Comment by Mmaxi1720** [comment]
Buenas Alex. 
Ahi lo deje como para que si o si se elija una opcion para jugar, y que no sea de forma aleatoria.
Aun estoy buscando la forma de como redireccionar a la parte de instrucciones en el caso de que nadie juegue despues del tiempo.
Pero estoy bloqueado con esa parte.
